name: LiteEssentials
version: ${project.version}
description: LiteEssentials is a plugin for Minecraft that provides a few useful features.
main: me.topeestla.essentials.LiteEssentials
autoUpdate: true
authors:
  - TopeEstLa
website: https://squid-developper.fr
libraries:
  - net.kyori:adventure-api:4.11.0
  - net.kyori:adventure-platform-bukkit:4.1.1
  - net.kyori:adventure-text-minimessage:4.11.0
  - com.fasterxml.jackson.core:jackson-core:2.13.3
  - com.fasterxml.jackson.core:jackson-databind:2.13.3
  - com.fasterxml.jackson.core:jackson-annotations:2.13.3
  - com.zaxxer:HikariCP:5.0.1
  - redis.clients:jedis:4.2.3